version: '3.8'

services:

  postgres:
    image: postgres:16.3-alpine3.20
    container_name: postgres
    ports:
      - ${POSTGRES_PORT}:5432
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    volumes:
      - 'db:/var/lib/postgresql/data'
    networks:
      - travel-manager

  api-travel-manager:
    build:
      context: .
    container_name: api-travel-manager
    ports:
      - ${PORT}:3333
      - 5555:5555
    environment:
      - PORT=${PORT}
      - HOST=${HOST}
      - DATABASE_URL=${DATABASE_URL}
      - FRONT_URL=${FRONT_URL}
    depends_on:
      - postgres
    networks:
      - travel-manager

networks:
  travel-manager:
    driver: bridge

volumes:
  db: