apiVersion: v1
kind: Service

metadata:
  name: travel-service
  labels:
    app: travel
spec:
  selector:
    app: travel
  type: ClusterIP
  ports:
    - name: travel-service
      protocol: TCP
      port: 3333
      targetPort: 3333